[build]
  command = "npm run build"
  publish = "dist"

# Launch the app at /app (and any sub-path)
[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200
